### ISSUE TITLE
tried to build can-workshop

### ISSUE THREAD

**Issue by pYr0x** [bitovi/steal-tools#143]
i downloaded can-workshop and tried to build a production version.

a stealconfig.js still exists.
i have created a Gruntfile.js like this:
```
module.exports = function (grunt) {
    grunt.initConfig({
        stealBuild: {
            default: {
                options: {
                    system: {
                        main: "canjs_workshop",
                        config: __dirname+"/stealconfig.js"
                    }
                }
            }
        }
    });
    grunt.loadNpmTasks('steal-tools');
    grunt.registerTask('build',['stealBuild']);
};
```
i'v got this error:

```
C:\wamp\www\canjs workshop>grunt build
Running "stealBuild:default" (stealBuild) task
OPENING: canjs_workshop
error [ReferenceError: window is not defined] ReferenceError: window is not defined
    at evalmachine.<anonymous>:3:12
    at stealInstantiateResult.execute (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\main.js:618:32)
    at linkDynamicModule (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\dist\system.js:540:32)
    at linkDynamicModule (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\dist\system.js:534:11)
    at linkDynamicModule (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\dist\system.js:534:11)
    at linkDynamicModule (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\dist\system.js:534:11)
    at link (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\dist\system.js:404:11)
    at Object.execute (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\dist\system.js:715:11)
    at link (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader-sans-promises.src.js:670:29)
    at doLink (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader-sans-promises.src.js:468:7)
ERROR: Cannot read property 'order' of undefined TypeError: Cannot read property 'order' of undefined
    at visit (C:\wamp\www\canjs workshop\node_modules\steal-tools\lib\graph\order.js:7:12)
    at C:\wamp\www\canjs workshop\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (C:\wamp\www\canjs workshop\node_modules\steal-tools\lib\graph\order.js:10:22)
    at module.exports (C:\wamp\www\canjs workshop\node_modules\steal-tools\lib\graph\order.js:16:2)
    at C:\wamp\www\canjs workshop\node_modules\steal-tools\lib\build\multi.js:116:4
    at Array.forEach (native)
    at C:\wamp\www\canjs workshop\node_modules\steal-tools\lib\build\multi.js:115:9
    at eval (eval at <anonymous> (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\traceur\src\node\traceur.js:24:17), <anonymous>:1621:100)
    at promiseHandle (eval at <anonymous> (C:\wamp\www\canjs workshop\node_modules\steal-tools\node_modules\traceur\src\node\traceur.js:24:17), <anonymous>:1715:20)
```

if i tried the sample on http://stealjs.com/docs/index.html#section_QuickStart the build process will work.

**Comment by justinbmeyer** [comment]
@pYr0x I can debug this with you tomorrow if you ping me on gitter: https://gitter.im/bitovi/steal

**Comment by matthewp** [comment]
Did this get worked out?

**Comment by matthewp** [comment]
Going to assume everything is fine here, please reopen if there is still an issue I can help with.
